Add support to use JNDI service with carbon-datasources in non-OSGi environment
wso2/carbon-datasources pull request #27
Opened 2017-01-05 18:57 UTC by Thanu

The JNDI service can be used with carbon-datasources in non-OSGi environment with the new changes introduced in carbon-jndi[[1]](https://github.com/wso2/carbon-jndi/pull/30).

If there is no jndi config defined explicitly in datasource definition, it will use the InMemoryInitialContextFactory to bind datasource objects to jndi context using carbon-jndi. A custom JNDI context can be plugged in easily by adding its initial context factory class in `jndiConfig` as below using the JNDI Context.INITIAL_CONTEXT_FACTORY("java.naming.factory.initial") property.

2017-01-09 05:54 UTC, Niranjan-K requested changes

2017-01-09 05:54 UTC, Niranjan-K commented on sample/spi-sample/README.md
>  JNDI configuration cannot be added to a datasource because JNDI support is not there for non-OSGi applications at the moment.
This needs to be corrected. With this PR, we will be able to change the JNDI configuration.

2017-01-10 08:17 UTC, Thanu commented
To merge this p/r, carbon-jndi has to be released with changes in [[1]](https://github.com/wso2/carbon-jndi/pull/30) and jndi version has to be updated in carbon-datasources.

2017-01-10 08:55 UTC, Niranjan-K commented on pom.xml
> +        <carbon.jndi.version>1.0.2-SNAPSHOT</carbon.jndi.version>
It is not advisable to depend on the snapshot version.

2017-01-13 10:48 UTC, Thanu commented on pom.xml
> +        <carbon.jndi.version>1.0.2-SNAPSHOT</carbon.jndi.version>
Will update the version once carbon-jndi is released.

2017-11-24 05:48 UTC, isudana commented
Please do suggested changes and resolve conflicts.

2017-12-18 06:07 UTC, Niranjan-K commented
Closing the PR since there are conflicts.

2017-12-18 06:07 UTC, closed without merging