Update kernel version to 5.2.0-m3
wso2/carbon-datasources pull request #30
Opened 2017-03-01 07:21 UTC by lmanohara

2017-03-01 07:27 UTC, lmanohara commented on pom.xml
> +        <carbon.jndi.version>1.0.2-SNAPSHOT</carbon.jndi.version>
Please add the jndi release version after merging https://github.com/wso2/carbon-jndi/pull/33.

2017-03-02 00:40 UTC, kasunbg requested changes

2017-03-02 00:40 UTC, kasunbg commented on pom.xml
> +                <version>${project.version}</version>
Instead of the ${project.version}, let's use ${carbon.datasource.version}

2017-03-02 00:40 UTC, kasunbg commented on pom.xml
> +                <version>${project.version}</version>
Instead of the ${project.version}, let's use ${carbon.datasource.version}

2017-03-02 00:40 UTC, kasunbg commented on pom.xml
> +        <carbon.jndi.version>1.0.2-SNAPSHOT</carbon.jndi.version>
@ChanakaCooray adding chanaka

2017-03-02 01:25 UTC, Niranjan-K commented
@lmanohara : Migrating to Kernel 5.2.0-m3 would mean moving the datasources.xml configuration to the deployment.yaml using the Carbon Config Provider. In this PR, only the Kernel version is changed, but moving the datasource configuration is not there.

2017-03-02 01:26 UTC, Niranjan-K requested changes
Migration to Kernel 5.2.0-m3 would require moving the datasource configuration from XML to deployment.yaml using the carbon config provider.

2017-03-06 13:12 UTC, laki88 commented on pom.xml
> +  ~ Copyright 2017 WSO2, Inc. (http://wso2.com)
We do not change year for changed files.

2017-06-28 10:05 UTC, Niranjan-K commented
Closing this PR as this commits are there in #33

2017-06-28 10:05 UTC, closed without merging