Update kernel version to 5.2.0-m3
wso2/carbon-datasources pull request #33
Opened 2017-03-14 09:15 UTC by daneshk

2017-03-14 10:26 UTC, vidurananayakkara commented on components/org.wso2.carbon.datasource.core/src/main/java/org/wso2/carbon/datasource/core/beans/DataSourceDefinition.java
> +        configMap.put("jdbcUrl", "jdbc:h2:./database/WSO2_CARBON_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000");
Should we have the keys as constants in here?

2017-03-14 11:45 UTC, vidurananayakkara commented on components/org.wso2.carbon.datasource.core/src/main/java/org/wso2/carbon/datasource/core/beans/DataSourceMetadata.java
> +@Configuration(description = "Data Source metadata configuration")
The hashCode method in this class simply returns -1. IMO this method should return an integer-specific to the object instance. (http://stackoverflow.com/questions/3563847/what-is-the-use-of-hashcode-in-java) Is there a specific reason for returning -1 in this method

2017-03-14 11:47 UTC, vidurananayakkara commented on components/org.wso2.carbon.datasource.core/src/main/java/org/wso2/carbon/datasource/core/beans/JNDIConfig.java
> +//        assert false : "hashCode() not implemented";
As mentioned in the previous comment, is there a specific reason for returning -1. Furthermore having commented code is considered as a code smell and therefore IMO we should remove this line. WDYT?

2017-03-14 11:50 UTC, vidurananayakkara commented on components/org.wso2.carbon.datasource.core/src/test/java/org/wso2/carbon/datasource/core/BaseTest.java
> +        Path configFilePath = Paths.get("src", "test", "resources", "conf", "deployment.yaml");
Should we have deployment.yaml file name as a constant in this class (Since the same file name is used in multiple places)

2017-03-14 11:59 UTC, vidurananayakkara commented on tests/test-distribution/pom.xml
> +                <version>${carbon.feature.plugin.version}</version>
Shouldn't this plugin be specified in the root pom within the `<build><pluginmanagement><plugins>` tag and then be used here? Then we do not need to specify the version of the plugin here and would be common throughout the project.

2017-03-14 15:17 UTC, daneshk commented on components/org.wso2.carbon.datasource.core/src/main/java/org/wso2/carbon/datasource/core/beans/DataSourceDefinition.java
> +        configMap.put("jdbcUrl", "jdbc:h2:./database/WSO2_CARBON_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000");
This default values are for the configure documentation. we don't use these keys anyway else. only in this class. do we need to specify keys as constants.

2017-03-14 15:18 UTC, daneshk commented on components/org.wso2.carbon.datasource.core/src/main/java/org/wso2/carbon/datasource/core/beans/DataSourceMetadata.java
> +@Configuration(description = "Data Source metadata configuration")
corrected. thanks.

2017-03-14 15:18 UTC, daneshk commented on components/org.wso2.carbon.datasource.core/src/main/java/org/wso2/carbon/datasource/core/beans/JNDIConfig.java
> +//        assert false : "hashCode() not implemented";
corrected. thanks.

2017-03-14 15:22 UTC, daneshk commented on components/org.wso2.carbon.datasource.core/src/test/java/org/wso2/carbon/datasource/core/BaseTest.java
> +        Path configFilePath = Paths.get("src", "test", "resources", "conf", "deployment.yaml");
corrected. thanks

2017-03-15 03:44 UTC, vidurananayakkara commented on components/org.wso2.carbon.datasource.core/src/main/java/org/wso2/carbon/datasource/core/beans/DataSourceDefinition.java
> +        configMap.put("jdbcUrl", "jdbc:h2:./database/WSO2_CARBON_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000");
If so we can keep as it is (no need to specify keys as constants)

2017-03-24 04:51 UTC, Niranjan-K commented
@daneshk : Can we have Git issues for the new commits please? Currently you have put the lengthy commit titles. It would have been better if we have lengthy description but in the commit body.

2017-06-07 06:04 UTC, imesh commented on components/org.wso2.carbon.datasource.core/src/main/java/org/wso2/carbon/datasource/core/DataSourceManager.java
> +                    throw new DataSourceException("configuration doesn't specify any datasource configurations");
Would it be more meaningful to make the first letter of the word "configuration" uppercase?

2017-06-07 06:05 UTC, imesh commented on components/org.wso2.carbon.datasource.core/src/main/java/org/wso2/carbon/datasource/core/DataSourceManager.java
> +                    logger.debug("Creating datasource object| datasource name: " + dsmInfo.getName());
What would be the reason to use the pipe character "object| datasource name"?

2017-06-07 06:17 UTC, Niranjan-K requested changes

2017-06-07 06:17 UTC, Niranjan-K commented on components/org.wso2.carbon.datasource.core/pom.xml
> +            <optional>true</optional>
If we are using this in the java code (in the default flow), then we shouldn't have this dependency as optional.

2017-06-07 06:17 UTC, Niranjan-K commented on components/org.wso2.carbon.datasource.core/pom.xml
> +            javax.xml.parsers;version=0.0.0,
We need to change this to a range, say 0.0.0 to 1.0.0

2017-06-07 06:17 UTC, Niranjan-K commented on components/org.wso2.carbon.datasource.core/src/main/java/org/wso2/carbon/datasource/rdbms/hikari/utils/HikariDataSourceUtils.java
> +            throw new DataSourceException("datasource configurations are not provided. datasource object will not be " +
Should start with a capital letter.

2017-06-07 06:17 UTC, Niranjan-K commented on components/org.wso2.carbon.datasource.core/src/main/java/org/wso2/carbon/datasource/rdbms/hikari/utils/HikariDataSourceUtils.java
> +                            .doPrivileged((PrivilegedAction<Object>) () -> {
we can move this to the same level as "AccessController"

2017-06-07 08:12 UTC, daneshk commented on components/org.wso2.carbon.datasource.core/src/main/java/org/wso2/carbon/datasource/core/DataSourceManager.java
> +                    logger.debug("Creating datasource object| datasource name: " + dsmInfo.getName());
Not specific reason. just wanted to separate the message.

2017-06-28 10:04 UTC, Niranjan-K approved these changes

2017-06-28 10:04 UTC, merged